name: Release

on:
  release:
    types: [created]    
    
env:
  BEAT_VERSION: 7.7.2-SNAPSHOT
  GITHUB_TOKEN: ${{ github.token }}
  
jobs:
  build:    
    name: Build
    runs-on: windows-latest
    steps:    
    - id: get_version
      uses: mirerosystem/get-version-action@v1.3
    - name: Get Release
      id: get_release
      uses: bruceadams/get-release@v1.2.0
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: beats
        # Directory containing files to upload
        path: ../../.././release            
